### ISSUE TITLE
Missing cards when importing custom deck

### ISSUE THREAD

**Issue by Baucmd** [Raffaelbdl/kuma-browser#14]
Hi, 

Thank you for developing such a great plugin, it's been really good and I have not encountered any problem expect this one !

I'm importing a custom desk from top X words that I created on jpdb.io, when I review the cards in anki after the import, several card seems to have gone missing, for exemple いる (id 1577980) is not present in the cards list.

![image](https://github.com/user-attachments/assets/b5b89827-3e41-4a60-a9b7-d221d73c7b41)
( the result is not いる it's 入いる)

I tried to see if the data fetched from the public API and it seems to be present:

![image](https://github.com/user-attachments/assets/dafd6354-f603-4cf9-b912-6af0f5192a06)

it seems that there is two meaning for いる(1546640 and 1577980), could it be the issue ? 

I have not checked the code yet, but do you know any problem on this topic ? 
I can take a look if you need :)

**Comment by Baucmd** [comment]
https://github.com/Raffaelbdl/kuma-browser/blob/0dddb6eeaff986a4ef51eda01aeb4032242265c9/kuma/jpdb_api.py#L247-L250


you are targeting the expression, both meaning have the same expression therefore iru (to be) is not written in anki deck

**Comment by Raffaelbdl** [comment]
Hi, thank you for using this addon !

Actually that is a known issue I should work on, I should store some kind of unique id for the cards. This would also allow to update the notes automatically even after the creation.

I will see if I can make something today, I have procrastinated on it for too long 😂

**Comment by Raffaelbdl** [comment]
Ok I think I managed to create some kind of note ID in the Pull Request. Could you try it and see if it fixes your problem in your case ?

Unfortunately this change is not backward compatible so if you had started learning your deck you might have to start again ^^'

**Comment by Baucmd** [comment]
Hi, 

Thank for your work, I'll try it tomorrow, I have managed to make it work by using SId and VId provided by JPDB that are both primary key of the vocabulary.

Here is the pull request on the fork I did 

https://github.com/Raffaelbdl/kuma-browser/pull/16

**Comment by Baucmd** [comment]
I think it's also resolve the problem of 

Cards from the API and the scraper are not "compatible", so duplicates will be created when trying to download from both

**Comment by Raffaelbdl** [comment]
Thank you for the PR! That is basically what I did as well, I just merged Sid and Vid into a single id to have a single entry for both normal cards and API cards.

To make cards "compatible" we would need a way to retrieve the Sid and Vid from the HTML page. I will try to dig into it again to see if I can find this information.

**Comment by Raffaelbdl** [comment]
So I have decided to go with only the VID for the identifier, as it can be immediately read from the url
If it is ok for you, I will push my PR and close this issue :hugs: 
Thank you for reminding me of this problem !

**Comment by Raffaelbdl** [comment]
I went ahead and merged it, please reopen the issue you want to add something :hugs:
